services:
  postgresql:
    container_name: employee-manager
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-db_employee}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgresql:
    driver: local
